# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# Adapted from https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/quantization/modelopt.py
# Petit NVFP4 量化配置与线性层方法实现，用于支持 AMD GPU 上的 NVFP4 量化推理


import logging  # 导入日志模块
from typing import Any, Dict, List, Optional  # 导入类型提示

import regex as re  # 导入正则表达式库
import torch  # 导入 PyTorch
from torch.nn.parameter import Parameter  # 导入参数类

from sglang.srt.layers.linear import LinearBase  # 导入线性层基类
from sglang.srt.layers.parameter import ModelWeightParameter, PerTensorScaleParameter  # 导入模型权重参数和逐张量缩放参数
from sglang.srt.layers.quantization.base_config import (  # 导入量化基础配置类
    LinearMethodBase,
    QuantizationConfig,
    QuantizeMethodBase,
)
from sglang.srt.layers.quantization.petit_utils import (  # 导入 Petit NVFP4 工具函数
    apply_petit_nvfp4_linear,
    prepare_nvfp4_layer_for_petit,
    verify_petit_nvfp4_supported,
)
from sglang.srt.layers.quantization.unquant import UnquantizedLinearMethod  # 导入非量化线性方法
from sglang.srt.layers.quantization.utils import is_layer_skipped  # 导入层跳过判断工具
from sglang.srt.utils import is_hip  # 导入 HIP 平台判断工具

_is_hip = is_hip()  # 判断当前是否为 AMD HIP 平台

# Initialize logger for the module  # 初始化模块日志记录器
logger = logging.getLogger(__name__)


# Configuration class to support the NVFP4 quantized model generated by the ModelOpt quantization tool
# 支持由 ModelOpt 量化工具生成的 NVFP4 量化模型的配置类
class PetitNvFp4Config(QuantizationConfig):
    """Config class for Petit FP4."""  # Petit FP4 配置类

    def __init__(  # 初始化方法
        self,
        is_checkpoint_nvfp4_serialized: bool = False,  # 检查点是否以 NVFP4 格式序列化
        kv_cache_quant_algo: str = None,  # KV 缓存量化算法
        group_size: int = None,  # 量化分组大小
        exclude_modules: List[str] = None,  # 排除量化的模块列表
    ) -> None:
        self.is_checkpoint_nvfp4_serialized = is_checkpoint_nvfp4_serialized  # 保存 NVFP4 序列化标志
        if is_checkpoint_nvfp4_serialized:  # 如果检查点是 NVFP4 格式
            logger.warning(  # 记录警告
                "Detected nvfp4 checkpoint. Please note that the "
                "format is experimental and subject to change."
            )  # 检测到 nvfp4 检查点，请注意该格式为实验性质，可能随时变更
        self.group_size = group_size  # 保存分组大小
        self.kv_cache_quant_algo = kv_cache_quant_algo  # 保存 KV 缓存量化算法
        self.exclude_modules = exclude_modules  # 保存排除模块列表

    @classmethod
    def get_name(cls) -> str:  # 获取量化方法名称
        return "petit_nvfp4"  # 返回 petit_nvfp4

    @classmethod
    def get_supported_act_dtypes(cls) -> List[torch.dtype]:  # 获取支持的激活数据类型
        return [torch.bfloat16, torch.half]  # 支持 bfloat16 和 half 精度

    @classmethod
    def get_min_capability(cls) -> int:  # 获取最低 GPU 计算能力要求
        # Petit supports the gfx90a and gfx942 GPUs  # Petit 支持 gfx90a 和 gfx942 GPU
        return 90  # 最低计算能力为 90

    @classmethod
    def get_config_filenames(cls) -> List[str]:  # 获取配置文件名列表
        return ["hf_quant_config.json"]  # 返回 HuggingFace 量化配置文件名

    @classmethod
    def from_config(cls, config: Dict[str, Any]) -> "PetitNvFp4Config":  # 从配置字典创建实例
        quant_config = cls.get_from_keys(config, ["quantization"])  # 获取量化配置
        quant_method = quant_config["quant_algo"]  # 获取量化算法名称
        group_size = quant_config.get("group_size", None)  # 获取分组大小
        verify_petit_nvfp4_supported(quant_method, group_size)  # 验证 Petit NVFP4 是否支持

        is_checkpoint_nvfp4_serialized = "NVFP4" in quant_method  # 判断量化方法是否为 NVFP4
        kv_cache_quant_algo = quant_config["kv_cache_quant_algo"]  # 获取 KV 缓存量化算法
        if not kv_cache_quant_algo:  # 如果未指定 KV 缓存量化算法
            kv_cache_quant_algo = "auto"  # 设为自动
        exclude_modules = quant_config.get("exclude_modules", None)  # 获取排除模块列表
        if not (group_size and kv_cache_quant_algo and (exclude_modules is not None)):  # 如果缺少必要参数
            logger.warning(  # 记录警告
                f"group_size: {group_size},"
                f"kv_cache_quant_algo: {kv_cache_quant_algo},"
                f"exclude_modules: {exclude_modules}"
            )  # 打印当前参数值
            raise ValueError(  # 抛出值错误
                "NVFP4 quantization requires group size and "
                "kv_cache_quant_algo specified in "
                "hf_quant_config.json"
            )  # NVFP4 量化需要在配置文件中指定 group_size 和 kv_cache_quant_algo
        return cls(  # 返回配置实例
            is_checkpoint_nvfp4_serialized,
            kv_cache_quant_algo,
            group_size,
            exclude_modules,
        )

    @classmethod
    def override_quantization_method(cls, hf_quant_cfg, user_quant) -> Optional[str]:  # 覆盖量化方法
        can_convert = cls.is_petit_nvfp4_compatible(hf_quant_cfg)  # 检查是否兼容 Petit NVFP4
        if can_convert:  # 如果兼容
            return cls.get_name()  # 返回 Petit NVFP4 方法名
        return None  # 否则返回 None

    @classmethod
    def is_petit_nvfp4_compatible(cls, quant_config: Dict[str, Any]) -> bool:  # 检查是否兼容 Petit NVFP4
        quant_method = quant_config.get("quant_method", "").lower()  # 获取量化方法名并转小写
        return _is_hip and quant_method == "modelopt"  # 仅在 HIP 平台且量化方法为 modelopt 时兼容

    def is_layer_excluded(self, prefix: str, exclude_modules: list):  # 判断层是否被排除量化
        for pattern in exclude_modules:  # 遍历排除模式列表
            regex_str = pattern.replace(".", r"\.").replace("*", r".*")  # 将通配符模式转为正则表达式
            if re.fullmatch(regex_str, prefix):  # 如果匹配成功
                return True  # 该层被排除
        return False  # 未被排除

    def get_quant_method(  # 获取量化方法
        self, layer: torch.nn.Module, prefix: str
    ) -> Optional["QuantizeMethodBase"]:
        if isinstance(layer, LinearBase):  # 如果是线性层
            if is_layer_skipped(prefix, self.exclude_modules) or self.is_layer_excluded(  # 如果该层被跳过或排除
                prefix, self.exclude_modules
            ):
                return UnquantizedLinearMethod()  # 返回非量化线性方法
            return PetitNvFp4LinearMethod(self)  # 返回 Petit NVFP4 线性方法
        return None  # 非线性层返回 None

    def get_scaled_act_names(self) -> List[str]:  # 获取需要缩放的激活名称列表
        return []  # 返回空列表


class PetitNvFp4LinearMethod(LinearMethodBase):  # Petit NVFP4 线性层方法
    """Linear method for NVFP4.  # NVFP4 线性方法
    Supports loading NVFP4 checkpoints with the following structure:  # 支持加载以下结构的 NVFP4 检查点：

    |Tensor Name           | datatype      |  shape      |  # 张量名 | 数据类型 | 形状
    |----------------------------------------------------|
    |input_scale           | torch.float32 | scalar      |  # 输入缩放因子 | float32 | 标量
    |weight                | NVFP4(SE2M1)  | [1, X, y/2] |  # 权重 | NVFP4 | [1, X, y/2]
    |weight_scale          | FP8-E4M3      | [X, Y]      |  # 权重缩放 | FP8-E4M3 | [X, Y]
    |weight_scale_2        | torch.float32 | scalar      |  # 二级权重缩放 | float32 | 标量

    The weights are quantized per block of 16 elements.  # 权重按每 16 个元素一组进行量化
    Args: quant_config: The ModelOpt quantization config.  # 参数: quant_config: ModelOpt 量化配置
    """

    def __init__(self, quant_config: PetitNvFp4Config):  # 初始化方法
        self.quant_config = quant_config  # 保存量化配置

    def create_weights(  # 创建权重参数
        self,
        layer: torch.nn.Module,  # 目标层
        input_size_per_partition: int,  # 每个分区的输入大小
        output_partition_sizes: List[int],  # 输出分区大小列表
        input_size: int,  # 输入总大小
        output_size: int,  # 输出总大小
        params_dtype: torch.dtype,  # 参数数据类型
        **extra_weight_attrs,  # 额外权重属性
    ):
        del input_size, output_size  # 删除未使用的变量
        if not self.quant_config.is_checkpoint_nvfp4_serialized:  # 如果检查点不是 NVFP4 格式
            raise ValueError(  # 抛出值错误
                "NVFP4 quantization was selected, "
                " dynamic quantization is not supported."
            )  # 选择了 NVFP4 量化，但不支持动态量化

        output_size_per_partition = sum(output_partition_sizes)  # 计算分区输出总大小
        weight_loader = extra_weight_attrs.get("weight_loader")  # 获取权重加载器

        layer.logical_widths = output_partition_sizes  # 保存逻辑宽度

        layer.input_size_per_partition = input_size_per_partition  # 保存分区输入大小
        layer.output_size_per_partition = output_size_per_partition  # 保存分区输出大小
        if input_size_per_partition % 16 != 0:  # 如果输入大小不是 16 的倍数
            raise ValueError(  # 抛出值错误
                "Unsupported model when in features size is " "not multiple of 16"
            )  # 输入特征大小不是 16 的倍数时不支持

        weight_dtype = (  # 确定权重缩放的数据类型
            torch.float8_e4m3fn  # NVFP4 检查点使用 FP8-E4M3
            if self.quant_config.is_checkpoint_nvfp4_serialized
            else params_dtype  # 否则使用参数默认类型
        )

        weight = ModelWeightParameter(  # 创建模型权重参数
            data=torch.empty(  # 分配空张量
                # 2 fp4 data is packed in one uint8 in the input dimension  # 2 个 fp4 数据在输入维度打包为一个 uint8
                output_size_per_partition,
                input_size_per_partition // 2,  # 输入维度减半，因为两个 fp4 打包为一个 uint8
                dtype=torch.uint8,  # 数据类型为 uint8
            ),
            input_dim=1,  # 输入维度索引
            output_dim=0,  # 输出维度索引
            weight_loader=weight_loader,  # 权重加载器
        )
        layer.register_parameter("weight", weight)  # 注册权重参数

        input_scale = PerTensorScaleParameter(  # 创建逐张量输入缩放参数
            data=torch.empty(len(output_partition_sizes), dtype=torch.float32),  # 每个输出分区一个缩放值
            weight_loader=weight_loader,  # 权重加载器
        )

        layer.register_parameter("input_scale", input_scale)  # 注册输入缩放参数

        weight_scale_2 = PerTensorScaleParameter(  # 创建二级权重缩放参数
            data=torch.empty(len(output_partition_sizes), dtype=torch.float32),  # 每个输出分区一个缩放值
            weight_loader=weight_loader,  # 权重加载器
        )
        layer.register_parameter("weight_scale_2", weight_scale_2)  # 注册二级权重缩放参数

        weight_scale = ModelWeightParameter(  # 创建权重缩放参数
            data=torch.empty(  # 分配空张量
                output_size_per_partition,  # 输出维度
                input_size_per_partition // self.quant_config.group_size,  # 按分组大小划分的维度
                dtype=weight_dtype,  # 权重缩放数据类型
            ),
            input_dim=1,  # 输入维度索引
            output_dim=0,  # 输出维度索引
            weight_loader=weight_loader,  # 权重加载器
        )

        layer.register_parameter("weight_scale", weight_scale)  # 注册权重缩放参数

    def process_weights_after_loading(self, layer: torch.nn.Module) -> None:  # 加载权重后处理
        input_scale_2 = layer.input_scale.max().to(torch.float32)  # 取输入缩放的最大值并转为 float32
        weight_scale_2 = layer.weight_scale_2.max().to(torch.float32)  # 取二级权重缩放的最大值并转为 float32
        layer.input_scale = Parameter(input_scale_2, requires_grad=False)  # 更新输入缩放为不可训练参数
        layer.weight_scale_2 = Parameter(weight_scale_2, requires_grad=False)  # 更新二级权重缩放为不可训练参数
        layer.alpha = Parameter(  # 计算并保存 alpha 缩放因子
            layer.input_scale * layer.weight_scale_2, requires_grad=False  # alpha = input_scale * weight_scale_2
        )

        prepare_nvfp4_layer_for_petit(layer)  # 准备层以适配 Petit 内核格式
        del layer.input_scale  # 删除不再需要的 input_scale

    def apply(  # 应用线性层计算
        self,
        layer: torch.nn.Module,  # 目标层
        x: torch.Tensor,  # 输入张量
        bias: Optional[torch.Tensor] = None,  # 偏置项
    ) -> torch.Tensor:
        return apply_petit_nvfp4_linear(  # 调用 Petit NVFP4 线性计算
            input=x,  # 输入张量
            weight=layer.weight,  # 权重
            weight_scale=layer.weight_scale,  # 权重缩放
            weight_scale_2=layer.weight_scale_2,  # 二级权重缩放
            size_n=layer.output_size_per_partition,  # 输出维度大小
            size_k=layer.input_size_per_partition,  # 输入维度大小
            bias=bias,  # 偏置项
        )  # 返回计算结果
